-- Estado inicial reproduzível para bancos PostgreSQL novos.

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    email VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    perfil VARCHAR(255) NOT NULL,
    versao BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE itens_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    categoria VARCHAR(255),
    codigo VARCHAR(255) NOT NULL,
    localizacao VARCHAR(255),
    nome VARCHAR(255) NOT NULL,
    quantidade_atual INTEGER NOT NULL,
    quantidade_minima INTEGER NOT NULL,
    versao BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_itens_estoque_codigo UNIQUE (codigo)
);

CREATE TABLE ferramentas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    categoria VARCHAR(255),
    localizacao VARCHAR(255),
    nome VARCHAR(255) NOT NULL,
    patrimonio VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    responsavel_atual_id BIGINT,
    versao BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_ferramentas_patrimonio UNIQUE (patrimonio)
);

CREATE TABLE movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    observacao VARCHAR(255),
    quantidade INTEGER NOT NULL,
    tipo_movimentacao VARCHAR(255) NOT NULL,
    item_estoque_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL
);

CREATE TABLE movimentacoes_ferramenta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    observacao VARCHAR(255),
    tipo_movimentacao VARCHAR(255) NOT NULL,
    ferramenta_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL
);
